# Local development overrides using 127.0.0.1 to match browser host
# Use with: bundle exec jekyll serve --config _config.yml,_config_dev.yml --host 127.0.0.1 --port 4000 --livereload
url: "http://127.0.0.1:4000"
baseurl: ""
environment: development
verbose: false
