# Local development overrides — prefer localhost for dev builds
# Use with: bundle exec jekyll serve --config _config.yml,_config_dev.yml --host localhost --port 4000 --livereload
url: "http://localhost:4000"
baseurl: ""
environment: development
verbose: false
