name: PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install bundler and dependencies
        run: |
          gem install bundler --conservative
          bundle config set path "vendor/bundle"
          bundle install --jobs 4 --retry 3

      - name: Configure preview variables
        id: vars
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          PREVIEW_PATH="pull/${PR_NUMBER}"
          echo "PR_NUMBER=${PR_NUMBER}" >> $GITHUB_OUTPUT
          echo "PREVIEW_PATH=${PREVIEW_PATH}" >> $GITHUB_OUTPUT

      - name: Override published:false for preview
        run: |
          # Replace `published: false` with `published: true` in posts, drafts and pages for preview builds
          set -euo pipefail
          git ls-files -z "_posts/**" "_drafts/**" "**/*.md" "**/*.markdown" | \
          while IFS= read -r -d '' file; do
            if [ -f "$file" ]; then
              perl -0777 -pe 's/^([ \t]*published:\s*)false$/\1true/gim' -i -- "$file" || true
            fi
          done

      - name: Build Jekyll preview
        env:
          JEKYLL_ENV: production
        run: |
          set -euo pipefail
          # Build with drafts and future posts enabled and set baseurl to the preview path
          PR_BASE="/${{ steps.vars.outputs.PREVIEW_PATH }}"
          echo "Building with baseurl=${PR_BASE}"
          bundle exec jekyll build --drafts --future --baseurl "${PR_BASE}" --config _config.yml --trace

      - name: Cleanup Windows alternate data streams from build
        run: |
          set -euo pipefail
          # Remove any files that include the Windows ADS suffix pattern ":Zone.Identifier" which breaks uploads
          find _site -type f -name '*:Zone.Identifier' -print0 | xargs -0 --no-run-if-empty rm -f || true
          # Also remove such files from the source assets (in case they were checked into the repo)
          find . -type f -name '*:Zone.Identifier' -print0 | xargs -0 --no-run-if-empty rm -f || true

      - name: Prepare deployment branch
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Use authenticated remote so pushes from the runner use the GITHUB_TOKEN
          AUTH_REMOTE="https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          git remote set-url origin "$AUTH_REMOTE"

          # Fetch latest gh-pages if it exists and create a local branch that matches remote
          git fetch origin gh-pages || true
          if git rev-parse --verify origin/gh-pages >/dev/null 2>&1; then
            # Ensure our local gh-pages matches remote (force-create local branch from remote)
            git checkout -B gh-pages origin/gh-pages
          else
            # No remote gh-pages yet: create orphan branch
            git checkout --orphan gh-pages
            git rm -rf . || true
            # create a minimal placeholder so branch isn't empty
            echo "" > .gitkeep
            git add .gitkeep
            git commit -m "chore: create gh-pages branch" || true
            git push origin gh-pages || true
          fi

      - name: Copy preview to gh-pages subtree
        run: |
          set -euo pipefail
          PR_DIR=${{ steps.vars.outputs.PREVIEW_PATH }}
          mkdir -p "$PR_DIR"
          
          # Copy built site into pull/<PR_NUMBER>/ directory, excluding files with colon characters
          rsync -a --delete --exclude='*:*' _site/ "$PR_DIR/"

          # Add and commit only if there are changes
          git add -A -- "$PR_DIR"
          if git diff --cached --quiet; then
            echo "No changes to deploy for PR #${{ steps.vars.outputs.PR_NUMBER }}"
          else
            git commit -m "Deploy PR #${{ steps.vars.outputs.PR_NUMBER }} preview"
            
            # Ensure we're up to date with remote and attempt to push
            git fetch origin gh-pages || true
            if git rev-parse --verify origin/gh-pages >/dev/null 2>&1; then
              git rebase --rebase-merges origin/gh-pages || true
            fi

            # Try push; if rejected, rebase and then try force-with-lease
            if ! git push origin gh-pages; then
              echo "Push rejected; attempting to pull --rebase and push again"
              git pull --rebase origin gh-pages || true
              if ! git push origin gh-pages; then
                echo "Push still rejected; attempting force-with-lease"
                git push --force-with-lease origin gh-pages || true
              fi
            fi
          fi

      - name: Post or update PR comment with preview URL
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const previewPath = `pull/${pr}/`;
            const previewUrl = `https://${owner}.github.io/${repo}/${previewPath}`;

            // Search for an existing bot comment
            const { data: comments } = await github.issues.listComments({ owner, repo, issue_number: pr });
            const botComment = comments.find(c => c.user && c.user.type === 'Bot' && c.body && c.body.includes('🧪 Preview ready'));

            const body = `🧪 Preview ready: ${previewUrl}\n\nBuilt with drafts + future posts. Updated on commit: ${context.sha}`;

            if (botComment) {
              await github.issues.updateComment({ owner, repo, comment_id: botComment.id, body });
            } else {
              await github.issues.createComment({ owner, repo, issue_number: pr, body });
            }
